### ISSUE TITLE
Error on startup: "unknown variant `DirectDownload`"

### ISSUE THREAD

**Issue by josiah-roberts** [atlanticaccent/starsector-mod-manager-rust#157] opened 2022-05-28 21:46 UTC
Linux dynamic:

```
error decoding response body: unknown variant `DirectDownload`, expected one of `Forum`, `ModdingSubforum`, `Discord`, `NexusMods`, `Index` at line 39 column 24

Caused by:
    unknown variant `DirectDownload`, expected one of `Forum`, `ModdingSubforum`, `Discord`, `NexusMods`, `Index` at line 39 column 24
```

Does not crash - impact unknown.

**Comment by atlanticaccent** [comment] 2022-07-01 22:05
Duplicate of #156

**Closed by atlanticaccent** 2022-07-01 22:05 UTC
